force-app/main/default/objects/Demo_Cleanup_Event__e/Demo_Cleanup_Event__e.object-meta.xml
<CustomObject>
    <description>Event generated by the batch deletion of records by the Demo Cleanup Lightning component.</description>
    <label>Demo Cleanup Event</label>
    <pluralLabel>Demo Cleanup Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Error_JSON_String__c.field-meta.xml
<CustomField>
    <fullName>Error_JSON_String__c</fullName>
    <description>A string containing a JSON array of objects containing error information.</description>
    <label>Error JSON String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Finished__c.field-meta.xml
<CustomField>
    <fullName>Finished__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if the demo cleanup task is finished, false otherwise.</description>
    <label>Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>The API name of the object whose records are being deleted.</description>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <description>The record ID of the demo cleanup task.</description>
    <label>Task Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Total_Errors__c.field-meta.xml
<CustomField>
    <fullName>Total_Errors__c</fullName>
    <description>The total number of errors so far.</description>
    <label>Total Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Total_Records_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Total_Records_Deleted__c</fullName>
    <description>The total number of records that have been deleted so far.</description>
    <label>Total Records Deleted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DemoCleanupBatch.cls
//  Batch date delete methods for the DemoCleanup Lightning component.
//
//  This code is provided AS IS, with no warranty or guarantee of suitability for use.
//  Contact: john.meyer@salesforce.com

global without sharing class DemoCleanupBatch implements Database.Batchable<sObject>, Database.Stateful, Database.RaisesPlatformEvents {
	private Id taskId;
	private String sObjectApiName;
	private String nameField;
	private String whereClause;
	private Boolean permanentlyDelete;

	private Integer totalRecordsProcessed = 0;
	private Integer totalErrors = 0;

	//  Class used by the execute() method to collect error information to send back to the component.

	private class ErrorSpec {
		private Id id;
		private String name;
		private String link;
		private String fields;
		private String message;
	}

	//  Constructor method that gathers the information for the batch job and builds the query string.
	//
	//  The parameters represent:
	//      taskId:  the Id of the task record specifying the cleanup task.
	//      sObjectApiName:  the API name of the object whose records we will delete.
	//      nameField:  the field containing the name of the object (usually 'Name', but could be something else ('CaseNumber' for Case, e.g.))
	//      whereClause:  the SOQL WHERE clause that identifies the records to be deleted.
	//      permanentlyDelete:  True if the records are to bypass the recycle bin and be permanently deleted.

	global DemoCleanupBatch(Id taskId, String sObjectApiName, String nameField, String whereClause, Boolean permanentlyDelete) {
		this.taskId = taskId;
		this.sObjectApiName = sObjectApiName;
		this.nameField = nameField;
		this.whereClause = whereClause;
		this.permanentlyDelete = permanentlyDelete;
	}

	//  Specify the query.

	global Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator('SELECT ' + this.nameField + ' FROM ' + this.sObjectApiName +
			(this.whereClause == null ? '' : ' WHERE ' + this.whereClause)
		);
	}

	//  Delete records by the batch.

	global void execute(Database.BatchableContext bc, List<sObject> chunk) {
		Integer recordNumber = 0;
		List<ErrorSpec> errors = new List<ErrorSpec>();

		for (Database.DeleteResult result : Database.delete(chunk, false)) {
			if (!result.isSuccess())
				for (Database.Error dberror : result.getErrors()) {
					ErrorSpec error = new ErrorSpec();
					error.id = result.getId();
					error.name = (String) chunk[recordNumber].get(this.nameField);
					error.link = '/lightning/r/' + this.sObjectApiName + '/' + result.getId() + '/view';
					error.fields = String.join(dberror.getFields(), ', ');
					error.message = dberror.getMessage();
					errors.add(error);
				}
			recordNumber++;
		}
		if (this.permanentlyDelete)
			Database.emptyRecycleBin(chunk);

		this.totalRecordsProcessed += chunk.size();
		this.totalErrors += errors.size();

		EventBus.publish(
			new Demo_Cleanup_Event__e(
				Task_Id__c = this.taskId,
				Finished__c = false,
				Object_API_Name__c = this.sObjectApiName,
				Total_Records_Deleted__c = this.totalRecordsProcessed,
				Total_Errors__c = this.totalErrors,
				Error_JSON_String__c = JSON.serialize(errors)
			)
		);
	}

	//  Make sure we notify the component that we are done.

	global void finish(Database.BatchableContext bc) {
		EventBus.publish(
			new Demo_Cleanup_Event__e(
				Task_Id__c = this.taskId,
				Finished__c = true,
				Object_API_Name__c = this.sObjectApiName,
				Total_Records_Deleted__c = this.totalRecordsProcessed,
				Total_Errors__c = this.totalErrors,
				Error_JSON_String__c = '[]'
			)
		);
	}
}