force-app/main/default/objects/Demo_Cleanup_Event__e/Demo_Cleanup_Event__e.object-meta.xml
<CustomObject>
    <description>Event generated by the batch deletion of records by the Demo Cleanup Lightning component.</description>
    <label>Demo Cleanup Event</label>
    <pluralLabel>Demo Cleanup Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Error_JSON_String__c.field-meta.xml
<CustomField>
    <fullName>Error_JSON_String__c</fullName>
    <description>A string containing a JSON array of objects containing error information.</description>
    <label>Error JSON String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Finished__c.field-meta.xml
<CustomField>
    <fullName>Finished__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if the demo cleanup task is finished, false otherwise.</description>
    <label>Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>The API name of the object whose records are being deleted.</description>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <description>The record ID of the demo cleanup task.</description>
    <label>Task Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Total_Errors__c.field-meta.xml
<CustomField>
    <fullName>Total_Errors__c</fullName>
    <description>The total number of errors so far.</description>
    <label>Total Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Total_Records_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Total_Records_Deleted__c</fullName>
    <description>The total number of records that have been deleted so far.</description>
    <label>Total Records Deleted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Event__e/fields/Total_Records_with_Errors__c.field-meta.xml
<CustomField>
    <fullName>Total_Records_with_Errors__c</fullName>
    <description>The total number of records that had errors so far. This is different from Total_Errors__c since a single row can have multiple errors.</description>
    <label>Total Records with Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Task__c/Demo_Cleanup_Task__c.object-meta.xml
<CustomObject>
    <description>A specification for the deletion of an object&apos;s records as part of a demo cleanup.</description>
    <label>Demo Cleanup Task</label>
    <nameField>
        <displayFormat>DCT-{0000}</displayFormat>
        <label>Demo Cleanup Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Cleanup Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Cleanup_Task__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>API Name of the object whose records are to be deleted.</description>
    <inlineHelpText>API Name of the object whose records are to be deleted.</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DemoCleanupApex.cls
/**
 *  Asynchronous Apex method invocation for the DemoCleanup Lightning component.
 *
 *  Copyright (c) 2021-2024, Salesforce.com, Inc.
 *  All rights reserved.
 *  SPDX-License-Identifier: BSD-3-Clause
 *  For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 *  @author john.meyer@salesforce.com
 *  @see    <a href="https://github.com/SFDC-Assets/Demo-Cleanup">Demo Cleanup documentation</a>
 */

public without sharing class DemoCleanupApex implements Queueable {

    private List<DemoCleanup.CleanupTask> cleanupTaskList;
    private Integer currentIndex;

    
    /**
     *  Constructor method that gathers the information for the queuable.
	 *
	 *  @param cleanupTaskList  the entire list of cleanup tasks.
	 *  @param currentIndex     the zero-based index into cleanupTaskList of the current cleanup task.
     */
 
    public DemoCleanupApex (List<DemoCleanup.CleanupTask> cleanupTaskList, Integer currentIndex) {
        this.cleanupTaskList = cleanupTaskList;
        this.currentIndex = currentIndex;
    }

    
    public void execute (QueueableContext context) {

        DemoCleanup.CleanupTask task = this.cleanupTaskList[this.currentIndex];

        EventBus.publish(
            new Demo_Cleanup_Event__e (
                Task_Id__c = task.itemId,
                Finished__c = false,
                Object_API_Name__c = null,
                Total_Records_Deleted__c = null,
                Total_Records_with_Errors__c = 0,
                Total_Errors__c = 0,
                Error_JSON_String__c = '[]'
            )
        );    
        try {
            ((DemoCleanupApexItem) Type.forName(task.itemApexClassName).newInstance()).execute(task.itemId);
            EventBus.publish(
                new Demo_Cleanup_Event__e (
                    Task_Id__c = task.itemId,
                    Finished__c = true,
                    Object_API_Name__c = null,
                    Total_Records_Deleted__c = null,
                    Total_Records_with_Errors__c = 0,
                    Total_Errors__c = 0,
                    Error_JSON_String__c = '[]'
                )
            );    
        } catch (Exception e) {
            DemoCleanup.ErrorSpec error = new DemoCleanup.ErrorSpec();
            error.id = task.itemId;
            error.name = task.itemDescription;
            error.link = '/lightning/r/Demo_Cleanup_Task__c/' + task.itemId + '/view';
            error.fields = null;
            error.message = 'Could not run the "execute" method of Apex class "' + task.itemApexClassName +
                '". Make sure it exists and implements the DemoCleanupApexItem interface.';
            EventBus.publish(
                new Demo_Cleanup_Event__e (
                    Task_Id__c = task.itemId,
                    Finished__c = true,
                    Object_API_Name__c = null,
                    Total_Records_Deleted__c = null,
                    Total_Records_with_Errors__c = 1,
                    Total_Errors__c = 1,
                    Error_JSON_String__c = JSON.serialize(new List<DemoCleanup.ErrorSpec> { error })
                )
            );    
        } finally {
            DemoCleanup.cleanup(this.cleanupTaskList, this.currentIndex + 1);
        }
    }

}