force-app/main/default/objects/Demo_Cleanup_Task__c/Demo_Cleanup_Task__c.object-meta.xml
<CustomObject>
    <description>A specification for the deletion of an object&apos;s records as part of a demo cleanup.</description>
    <label>Demo Cleanup Task</label>
    <nameField>
        <displayFormat>DCT-{0000}</displayFormat>
        <label>Demo Cleanup Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Cleanup Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Cleanup_Task__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if this item should be included in the list of tasks.</description>
    <inlineHelpText>Checked if this item should be included in the list of tasks.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A description of the demo cleanup item, for example, &quot;Delete all records that are not custom-crafted for the demo scenario&quot;.</description>
    <inlineHelpText>A description of the demo cleanup item, for example, &quot;Delete all records that are not custom-crafted for the demo scenario&quot;.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Task__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>API Name of the object whose records are to be deleted.</description>
    <inlineHelpText>API Name of the object whose records are to be deleted.</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Task__c/fields/Permanently_Delete__c.field-meta.xml
<CustomField>
    <fullName>Permanently_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if records of this object should bypass the recycle bin and be permanently deleted.</description>
    <inlineHelpText>Checked if records of this object should bypass the recycle bin and be permanently deleted.</inlineHelpText>
    <label>Permanently Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Cleanup_Task__c/fields/SOQL_WHERE_Clause__c.field-meta.xml
<CustomField>
    <fullName>SOQL_WHERE_Clause__c</fullName>
    <description>A SOQL WHERE clause expression (without the &quot;WHERE&quot;) that evaluates to &quot;true&quot; if a record should be deleted, for example, &quot;Hand_Crafted_for_Demo_Scenario__c = false&quot;. Leave blank if all records of this object are to be deleted.</description>
    <inlineHelpText>A SOQL WHERE clause expression (without the &quot;WHERE&quot;) that evaluates to &quot;true&quot; if a record should be deleted, for example, &quot;Hand_Crafted_for_Demo_Scenario__c = false&quot;. Leave blank if all records of this object are to be deleted.</inlineHelpText>
    <label>SOQL WHERE Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DemoCleanup.cls
//  Controller for the DemoCleanup Lightning component.
//  
//  This code is provided AS IS, with no warranty or guarantee of suitability for use.
//  Contact: john.meyer@salesforce.com


public without sharing class DemoCleanup {
    
    public class CleanupTask {
        @AuraEnabled public Id itemId;
        @AuraEnabled public String itemDescription;
        @AuraEnabled public Boolean itemPermanentlyDelete;
        @AuraEnabled public String itemLink;
        @AuraEnabled public Integer itemCount;
        @AuraEnabled public Boolean itemQueryError;
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<CleanupTask> getCleanupTasks () {
        
        List<Demo_Cleanup_Task__c> demoCleanupTasks = [
            SELECT Object_API_Name__c, Description__c, SOQL_WHERE_Clause__c, Permanently_Delete__c
            FROM   Demo_Cleanup_Task__c
            WHERE  Active__c = true
            ORDER BY Name ASC
        ];
        
        if (demoCleanupTasks.IsEmpty())
            return null;
        else {
            List<CleanupTask> cleanupTasks = new List<CleanupTask>();
            for (Demo_Cleanup_Task__c cleanupItem : demoCleanupTasks) {
                CleanupTask item = new CleanupTask();
                item.itemId = cleanupItem.Id;
                item.itemLink = '/lightning/r/Demo_Cleanup_Task__c/' + cleanupItem.Id + '/view';
                item.itemDescription = cleanupItem.Description__c;
                item.itemPermanentlyDelete = cleanupItem.Permanently_Delete__c;
                try {
                    item.itemCount = Database.countQuery('SELECT count() FROM ' + cleanupItem.Object_API_Name__c +
                        cleanupItem.SOQL_WHERE_Clause__c != null ? ' WHERE ' + cleanupItem.SOQL_WHERE_Clause__c : '');
                    item.itemQueryError = false;
                } catch (QueryException e) {
                    item.itemCount = 0;
                    item.itemQueryError = true;
                }                
                cleanupTasks.add(item);
            }
            return cleanupTasks;
        }        
    }    
    
    
    //  Resets the demo by deleting superfluous records created during previous demo runs.
    
    @AuraEnabled
    public static void demoCleanup (List<Id> taskItems) {
        List<Demo_Cleanup_Task__c> cleanupTasks = [
            SELECT Object_API_Name__c, SOQL_WHERE_Clause__c, Permanently_Delete__c
            FROM   Demo_Cleanup_Task__c
            WHERE  Id IN :taskItems AND Active__c = true
            ORDER BY Name ASC
        ];
        for (Demo_Cleanup_Task__c item : cleanupTasks)
            Database.executeBatch(new DemoCleanupBatch(item.Object_API_Name__c, item.SOQL_WHERE_Clause__c, item.Permanently_Delete__c));
    }
}